### ISSUE TITLE
Add -v flag

### ISSUE THREAD

**Issue by perlun** [perlun/perlang#31]
At the moment, there's no easy way to get the version from an installed Perlang runtime. The following command should work as expected:

```shell
$ perlang -v
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/home/per/.perlang/bin/-v'.
File name: '/home/per/.perlang/bin/-v'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.ReadAllBytes(String path)
   at Perlang.ConsoleApp.Program.RunFile(String path)
   at Perlang.ConsoleApp.Program.Main(String[] args)
Aborted
```

## MRI Ruby behavior

```shell
$ ruby -v
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
```

## Python behavior

```shell
$ python -V
Python 2.7.16
```

**Comment by perlun** [comment]
As of #32, the version number (including git revision) is easily accessible so we should just add the missing `-v` flag and be able to close this issue.

**Comment by perlun** [comment]
Fixed in #36, closing.

**Comment by perlun** [comment]
It would be nice to get these two things as well:

- Support for `-v`. I am currently not aware on how to get this done with `System.CommandLine`.
- Adding the build date in the output as well. Again, unsure on how to get this done.

**Comment by perlun** [comment]
> * Support for `-v`. I am currently not aware on how to get this done with `System.CommandLine`.

This has subsequently been accomplished (the flag is now `-V` or `--version`). :tada: 

> * Adding the build date in the output as well. Again, unsure on how to get this done.

This is actually not done. But we have the git commit (`built from git commit 44485bb`), so perhaps that's good enough for now.
