### ISSUE TITLE
Bug: Invalid Typeref token on startup

### ISSUE THREAD

**Issue by perlun** [perlun/perlang#41]
I often run into the following error when starting Perlang on my local machine. So far, I've _only_ seen it on my development machine; on my "work" machine (where I just use Perlang for various trivial tasks), I've never seen it happen yet.

The weirdest thing: whenever this happen, I just run the same `perlang` command again, and then it typically works. Very odd!

```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
[/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Perlang.Interpreter.PerlangInterpreter.<>c.<RegisterCallables>b__9_0(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Perlang.Interpreter.PerlangInterpreter.RegisterCallables()
   at Perlang.Interpreter.PerlangInterpreter..ctor(Action`1 runtimeErrorHandler, Action`1 standardOutputHandler, IEnumerable`1 arguments)
   at Perlang.ConsoleApp.Program..ctor(IEnumerable`1 arguments)
   at Perlang.ConsoleApp.Program.<>c.<Main>b__4_0(ParseResult parseResult, IConsole console)
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
System.BadImageFormatException: [/home/per/.perlang/bin/System.Reflection.Metadata.dll] Invalid Typeref token.
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

Some trivial googling brought me to https://github.com/dotnet/core/issues/3763, I guess this could be the root cause at hand here.

**Comment by perlun** [comment]
I haven't seen this for a while. Perhaps it's gone away? Resolving issue for now, can re-open if it turns up again.

**Comment by perlun** [comment]
Hasn't happened since last year. Also, see #199 which could be potentially semi-related.
